CREATE SCHEMA IF NOT EXISTS proyecto;

CREATE TABLE IF NOT EXISTS proyecto.USUARIO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    usuario VARCHAR(100) NOT NULL,
    contrasena VARCHAR(100) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL,
    foto VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS proyecto.CATEGORIA (
    id INT PRIMARY KEY AUTO_INCREMENT,
    categoria VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS proyecto.RECURSO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    imagen VARCHAR(50) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    ruta VARCHAR(50),
    id_categoria INT NOT NULL,
    FOREIGN KEY (id_categoria) REFERENCES proyecto.CATEGORIA(id)
);

CREATE TABLE IF NOT EXISTS proyecto.FAVORITO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_usuario INT NOT NULL,
    id_recurso INT NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES proyecto.USUARIO(id),
    FOREIGN KEY (id_recurso) REFERENCES proyecto.RECURSO(id)
);



CREATE TABLE IF NOT EXISTS proyecto.CALIFICACION (
    id INT PRIMARY KEY AUTO_INCREMENT,
    punteo INT NOT NULL,
    comentario VARCHAR(100) NOT NULL,
    id_recurso INT NOT NULL,
    FOREIGN KEY (id_recurso) REFERENCES proyecto.RECURSO(id)
);