USE practica1;

INSERT INTO USER (user, pass, fullName) VALUES
('user1', 'pass123', 'John Smith'),
('alice21', 'hello@321', 'Alice Johnson'),
('johndoe', 'secret123', 'John Doe'),
('sarah87', 'mypass456', 'Sarah Thompson'),
('mike_34', 'ilovemydog', 'Mike Brown'),
('emmaG', 'p@ssw0rd!', 'Emma Garcia'),
('coolguy', 'letmein321', 'James Cool'),
('lisa_m', 'passpass', 'Lisa Miller'),
('tony99', 't0nyp@ss', 'Tony Anderson'),
('rachel22', 'rachelRocks', 'Rachel Lee'),
('sam123', 'samP@55', 'Sam Wright'),
('sophie78', 'il0vesophie', 'Sophie Adams'),
('max_cool', 'm@xRul3z', 'Max Cooper'),
('user22', 'myp@ssword', 'Emily Brown'),
('chris_23', 'chrisC0des', 'Chris Johnson'),
('lily2000', 'l1ly!123', 'Lily Taylor'),
('jack87', 'jackP@ss', 'Jack Evans'),
('anna.m', 'ann@123', 'Anna Martinez'),
('benjam1n', 'b3nny', 'Benjamin Wright'),
('sophia1', 'sophia!123', 'Sophia Martinez');

INSERT INTO ALBUM (albumName, userId) VALUES
('Foto de perfil', 1),
('Foto de perfil', 2),
('Foto de perfil', 3),
('Foto de perfil', 4),
('Foto de perfil', 5),
('Foto de perfil', 6),
('Foto de perfil', 7),
('Foto de perfil', 8),
('Foto de perfil', 9),
('Foto de perfil', 10),
('Foto de perfil', 11),
('Foto de perfil', 12),
('Foto de perfil', 13),
('Foto de perfil', 14),
('Foto de perfil', 15),
('Foto de perfil', 16),
('Foto de perfil', 17),
('Foto de perfil', 18),
('Foto de perfil', 19),
('Foto de perfil', 20),
('Mascotas favoritas', 1),
('Mascotas de la familia', 2),
('Amigos peludos', 3),
('Momentos con mis mascotas', 4),
('Perros y gatos', 5),
('Aventuras caninas', 6),
('Gatitos adorables', 7),
('Paseos con mi perro', 8),
('Compañeros de cuatro patas', 9),
('Animalitos divertidos', 10),
('Historias de mascotas', 11),
('Recuerdos con mi perro', 12),
('Diversión felina', 13),
('Mascotas en la naturaleza', 14),
('Mis queridos animales', 15),
('Viajes con mi perro', 16),
('Momentos deportivos con mascotas', 17),
('Mascotas y aventuras', 18),
('Mi mejor amigo peludo', 19),
('Travesuras de mascotas', 20);


INSERT INTO IMAGE (photo, albumId) VALUES
('Fotos_Perfil/foto1.jpg', 1),
('Fotos_Perfil/foto2.jpg', 1),
('Fotos_Perfil/foto3.jpg', 2),
('Fotos_Perfil/foto4.jpg', 2),
('Fotos_Perfil/foto5.jpg', 3),
('Fotos_Perfil/foto6.jpg', 3),
('Fotos_Perfil/foto7.jpg', 4),
('Fotos_Perfil/foto8.jpg', 4),
('Fotos_Perfil/foto9.jpg', 5),
('Fotos_Perfil/foto10.jpg', 5),
('Fotos_Perfil/foto11.jpg', 6),
('Fotos_Perfil/foto12.jpg', 6),
('Fotos_Perfil/foto13.jpg', 7),
('Fotos_Perfil/foto14.jpg', 7),
('Fotos_Perfil/foto15.jpg', 8),
('Fotos_Perfil/foto16.jpg', 8),
('Fotos_Perfil/foto17.jpg', 9),
('Fotos_Perfil/foto18.jpg', 9),
('Fotos_Perfil/foto19.jpg', 10),
('Fotos_Perfil/foto20.jpg', 10);
