CREATE SCHEMA IF NOT EXISTS practica2;

CREATE TABLE IF NOT EXISTS practica2.USER (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(100) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    fullName VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS practica2.ALBUM (
    id INT PRIMARY KEY AUTO_INCREMENT,
    albumName VARCHAR(100) NOT NULL,
    userId INT NOT NULL,
    FOREIGN KEY (userId) REFERENCES practica2.USER(id)
);

CREATE TABLE IF NOT EXISTS practica2.IMAGE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    photo VARCHAR(100) NOT NULL,
    descriptionn VARCHAR(500) NOT NULL,
    albumId INT NOT NULL,
    FOREIGN KEY (albumId) REFERENCES practica2.ALBUM(id)
);
